[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
geist_amm = "HTHyAbn3YXReoNWRczVasQkocnbXB4TASkjMpHrEGS9Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
update-sdk-idl = "cp ./target/types/geist_amm.ts ./sdk/src/idl && cp ./target/idl/geist_amm.json ./sdk/src/idl"
