[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
geist_amm = "AVzr6agjgPNhh4i4bTRLt9rLv48Nj4v5qKxMvgYty21n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
update-sdk-idl = "cp ./target/types/geist_amm.ts ./sdk/idl && cp ./target/idl/geist_amm.json ./sdk/idl"
