/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type AddLiquidityArgs = {
  poolId: beet.bignum
  deposits: beet.bignum[]
}

/**
 * @category userTypes
 * @category generated
 */
export const addLiquidityArgsBeet =
  new beet.FixableBeetArgsStruct<AddLiquidityArgs>(
    [
      ['poolId', beet.u64],
      ['deposits', beet.array(beet.u64)],
    ],
    'AddLiquidityArgs'
  )
