/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type Fees = {
  liquidityProvisionFeeBps: beet.bignum
  liquidityRemovalFeeBps: beet.bignum
  swapFeeBps: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const feesBeet = new beet.BeetArgsStruct<Fees>(
  [
    ['liquidityProvisionFeeBps', beet.u64],
    ['liquidityRemovalFeeBps', beet.u64],
    ['swapFeeBps', beet.u64],
  ],
  'Fees'
)
