/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { Fees, feesBeet } from '../types/Fees'

/**
 * @category Instructions
 * @category InitializeMultiPool
 * @category generated
 */
export type InitializeMultiPoolInstructionArgs = {
  amp: beet.bignum
  nTokens: beet.bignum
  initialDeposits: beet.bignum[]
  fees: Fees
}
/**
 * @category Instructions
 * @category InitializeMultiPool
 * @category generated
 */
export const initializeMultiPoolStruct = new beet.FixableBeetArgsStruct<
  InitializeMultiPoolInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amp', beet.u64],
    ['nTokens', beet.u64],
    ['initialDeposits', beet.array(beet.u64)],
    ['fees', feesBeet],
  ],
  'InitializeMultiPoolInstructionArgs'
)
/**
 * Accounts required by the _initializeMultiPool_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] core
 * @property [_writable_] multiPool
 * @property [_writable_] lpToken
 * @property [_writable_] lpTokenAdminAta
 * @category Instructions
 * @category InitializeMultiPool
 * @category generated
 */
export type InitializeMultiPoolInstructionAccounts = {
  admin: web3.PublicKey
  core: web3.PublicKey
  multiPool: web3.PublicKey
  lpToken: web3.PublicKey
  lpTokenAdminAta: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeMultiPoolInstructionDiscriminator = [
  78, 78, 68, 56, 116, 213, 188, 215,
]

/**
 * Creates a _InitializeMultiPool_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeMultiPool
 * @category generated
 */
export function createInitializeMultiPoolInstruction(
  accounts: InitializeMultiPoolInstructionAccounts,
  args: InitializeMultiPoolInstructionArgs,
  programId = new web3.PublicKey('AVzr6agjgPNhh4i4bTRLt9rLv48Nj4v5qKxMvgYty21n')
) {
  const [data] = initializeMultiPoolStruct.serialize({
    instructionDiscriminator: initializeMultiPoolInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.core,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.multiPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lpToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lpTokenAdminAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
