/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { SwapArgs, swapArgsBeet } from '../types/SwapArgs'

/**
 * @category Instructions
 * @category Swap
 * @category generated
 */
export type SwapInstructionArgs = {
  args: SwapArgs
}
/**
 * @category Instructions
 * @category Swap
 * @category generated
 */
export const swapStruct = new beet.FixableBeetArgsStruct<
  SwapInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', swapArgsBeet],
  ],
  'SwapInstructionArgs'
)
/**
 * Accounts required by the _swap_ instruction
 *
 * @property [_writable_, **signer**] user
 * @property [_writable_] core
 * @property [_writable_] pool
 * @property [_writable_] stablecoinInput
 * @property [_writable_] stablecoinOutput
 * @property [_writable_] stablecoinInputVault
 * @property [_writable_] stablecoinOutputVault
 * @property [_writable_] stablecoinInputUserAta
 * @property [_writable_] stablecoinOutputUserAta
 * @category Instructions
 * @category Swap
 * @category generated
 */
export type SwapInstructionAccounts = {
  user: web3.PublicKey
  core: web3.PublicKey
  pool: web3.PublicKey
  stablecoinInput: web3.PublicKey
  stablecoinOutput: web3.PublicKey
  stablecoinInputVault: web3.PublicKey
  stablecoinOutputVault: web3.PublicKey
  stablecoinInputUserAta: web3.PublicKey
  stablecoinOutputUserAta: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const swapInstructionDiscriminator = [
  248, 198, 158, 145, 225, 117, 135, 200,
]

/**
 * Creates a _Swap_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Swap
 * @category generated
 */
export function createSwapInstruction(
  accounts: SwapInstructionAccounts,
  args: SwapInstructionArgs,
  programId = new web3.PublicKey('AVzr6agjgPNhh4i4bTRLt9rLv48Nj4v5qKxMvgYty21n')
) {
  const [data] = swapStruct.serialize({
    instructionDiscriminator: swapInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.core,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinInput,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinOutput,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinInputVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinOutputVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinInputUserAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stablecoinOutputUserAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
